export const iconNames = {
  web_app_icons: [
    "adjust",
    "american-sign-language-interpreting",
    "anchor",
    "archive",
    "area-chart",
    "arrows",
    "arrows-h",
    "arrows-v",
    "assistive-listening-systems",
    "asterisk",
    "at",
    "audio-description",
    "balance-scale",
    "ban",
    "bar-chart",
    "barcode",
    "bars",
    "battery-empty",
    "battery-full",
    "battery-half",
    "battery-quarter",
    "battery-three-quarters",
    "bed",
    "beer",
    "bell",
  ],
  a11y: [
    "american-sign-language-interpreting",
    "assistive-listening-systems",
    "audio-description",
    "blind",
    "braille",
    "cc",
    "deaf",
    "low-vision",
    "question-circle-o",
    "sign-language",
    "tty",
    "universal-access",
    "volume-control-phone",
    "wheelchair",
    "wheelchair-alt",
  ],
  hand: [
    "hand-lizard-o",
    "hand-o-down",
    "hand-o-left",
    "hand-o-right",
    "hand-o-up",
    "hand-paper-o",
    "hand-peace-o",
    "hand-pointer-o",
    "hand-rock-o",
    "hand-scissors-o",
    "hand-spock-o",
    "thumbs-down",
    "thumbs-o-down",
    "thumbs-o-up",
    "thumbs-up",
  ],
} as const;

export type IconsType = keyof typeof iconNames;
export type IconName = (typeof iconNames)[IconsType][number];
